### ISSUE TITLE
Gyorsítás engedélyezése felhsználónak

### ISSUE THREAD

**Issue by MrMooss** [SzFMV2023-Tavasz/AutomatedCar-A#154]
Feladat:

- Gázpedál lenyomására gyorsítás engedélyezése
- Bekapcsolás, ha az autó vissza lassult a beállított sebességre

**Comment by DannyT21** [comment]
Apró módosítás: a Gázpedál elengedése után kapcsol vissza az ACC, tehát nem a természetes lassulás lassít, hanem maga az ACC kezd el visszalassítani a célsebességre.
Plusz feladat: AEB aktiválására kikapcsol ACC.
2 apró bugfix.
