### ISSUE TITLE
NPC felvétele: oval.json

### ISSUE THREAD

**Issue by mayerbarna** [SzFMV2023-Tavasz/AutomatedCar-A#27]
# NPC felvétele: oval.json **_1/A_**

**Fájl:** 
- oval.json

**Feladat:** 
- 1db Car
- 1db Pedestrian objektum felvétele 

**DoD:**

- [ ]  a megfelelő helyen jelennek meg a felvett objektumok
- [ ] vannak unit tesztek
- [ ] az összes unit teszt átment

**Comment by mayerbarna** [comment]
Megkell nézni, de mivel az oval.json csak az út elemeket tartalmazza, így ez a lépés szerintem elhagyható és a 7. pontnál direktbe kellene betölteni az autókat, gyalogosokat. pl: App.xaml.cs -> CreateControlledCar

**Comment by koloskaposzta** [comment]
@mayerbarna itt annyi a feladat hogy kezdo koordinatakat kell felvenni a jsonba a gyalogosnak és a kocsinak?

**Comment by mayerbarna** [comment]
@koloskaposzta

Kezdetben így beszéltük meg, viszont szerintem nem  json-be kellene felvenni ezeket a kezdő pozikat, hanem sokkal egyszerűbb ha az App.xaml.cs - ben a megfelelő metódusban (ezt látni fogod, oda comment-eltem) létrehozod őket egy random helyen

**Comment by koloskaposzta** [comment]
es melyik branchben?

**Comment by mayerbarna** [comment]
Bemergeltem már a develop-ba, a pályaválasztóval együtt ment be.
