### ISSUE TITLE
ACC Interface implementation

### ISSUE THREAD

**Issue by PMrtn** [SzFMV2023-Tavasz/AutomatedCar-A#44]
### **Inputs/Dependencies:**
► VirtualFunctionBus

### **Outputs:**
► Reference speed

### **Acceptance criteria**
► ACC interface is available

**Comment by GWI992** [comment]
This component belongs to Team-A3. 
See below: [Adaptív tempomat#6](https://github.com/SzFMV2023-Tavasz/AutomatedCar-A/issues/6)
